#+setupfile: "~/org/aux/setupfile.org"



* setup								   :noexport:

#+name: setup
#+begin_src R :session r :exports none :results silent

library(ggplot2)
library(ascii)
options(asciiType="org")

#+end_src

* todos

** todo [0/5]  siding prep
- [ ] pull bottom board and nails from board above
- [ ] snap chalk line 3" above sheathing bottom edge
- [ ] rip sheathing with circular saw
- [ ] pull off strip of sheathing
- [ ] pull/pound in all nails

* Overview

For a few years, I've noticed the garage door trim rotting on both the access door and
garage door. I decided to replace both old doors as well as the trim. In the process, I
observed softening and possible rotting on the bottom edge of a fair amount of the siding
on the garage. I pulled some of the boom trim to find fairly dark edges on the pressed
fiber sheathing. In addition, the foil-backed paper wrap was paper side out, and had water
marks along its entire width.

We had several questions and options at this point...
- were the water marks recent (from current siding)?
- where was the water coming from?
- were things just softened from time/water, or were they actually rotted?
- how high up was the potential damage?
- replace all the siding?
- replace just damaged boards?
- pull boards, re-wrap the house, and replace?

After examining the water stain patterns, it was observed that the short lengths of siding
between a door and a corner had stains the full height of a 12" board at the edges, but
only a couple of inches of staining in the center. This seemed to indicate that the water
entered behind the siding at the rotting door trim (possibly separated caulk) and at the
aluminum corners. Several of the corners looked to have been bumped over time, denting in
the corner itself, which flares the edges away from the siding. A pattern of stains was
also observed on a differnt side of the house corresponding to the nail spacing above.

With these facts in mind, we decided to remove all bottom siding boards and replace
them. In addition, the bottom 3" of sheathing was cut away and replaced with two strips of
1.5" high x  0.5" thick cut from a treated 2x4. Stainless steel ring shank nails were used
to fasten the replacement sheathing and the new siding. All corner caps were removed and
replaced after first caulking joining surfaces to ensure a water tight seal.


