<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#orgheadline12">1. setup</a>
<ul>
<li><a href="#orgheadline1">1.1. </a></li>
<li><a href="#orgheadline3">1.2. the life of a product developer</a>
<ul>
<li><a href="#orgheadline2">1.2.1. direct</a></li>
</ul>
</li>
<li><a href="#orgheadline5">1.3. the life of a product developer</a>
<ul>
<li><a href="#orgheadline4">1.3.1. indirect</a></li>
</ul>
</li>
<li><a href="#orgheadline6">1.4. but what the hell does emacs have to do with it?</a></li>
<li><a href="#orgheadline8">1.5. some competition</a>
<ul>
<li><a href="#orgheadline7">1.5.1. recording work</a></li>
</ul>
</li>
<li><a href="#orgheadline10">1.6. some competition</a>
<ul>
<li><a href="#orgheadline9">1.6.1. <span class="todo niltodo">todo</span> s</a></li>
</ul>
</li>
<li><a href="#orgheadline11">1.7. ok, so what is it?</a></li>
</ul>
</li>
</ul>
</div>
</div>


# setup<a id="orgheadline12"></a>

---
title       : Org-mode + R = awesome!
subtitle    : 
author      : John Henderson
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## <a id="orgheadline1"></a>

```{r echo=F}
img <- readPNG("../img/org-mode.png")
grid.raster(img)
```

---

## the life of a product developer<a id="orgheadline3"></a>

Stuff I do in the course of my work (probably not that different from you!):

### direct<a id="orgheadline2"></a>

-   write up experimental plans
-   do experiments
-   collect and analyze data
-   writeup reports and presentations
-   collaborate with colleagues

---

## the life of a product developer<a id="orgheadline5"></a>

### indirect<a id="orgheadline4"></a>

-   record all sorts info
-   meeting notes
-   todos
-   store contact info/notes
-   what to work on and when

---

## but what the hell does emacs have to do with it?<a id="orgheadline6"></a>

Believe it or not, I *learned Emacs* for `org-mode`. To date, it's the *only* solution I'm
aware of that allows for all of the following in one place:

-   notes
-   todos/time stamping/deadlines
-   tags
-   embedded code + execution
-   export to multiple formats, with images, links, table of contents, automatically
    generated code blocks and/or results&#x2026;

*Pretty cool!*

---

## some competition<a id="orgheadline8"></a>

I've always been a note taker as I like to refer to the past&#x2026; you never know what
might be useful in the future! I tried all sorts of programs:

### recording work<a id="orgheadline7"></a>

-   Word/Writer
-   [zim](http://zim-wiki.org/) (personal wiki)
-   [Evernote](https://evernote.com/)
-   [TiddlyWiki](http://tiddlywiki.com/)
-   [RStudio](https://www.rstudio.com/)?

---

## some competition<a id="orgheadline10"></a>

### todo s<a id="orgheadline9"></a>

-   [`todo.txt`](http://todotxt.com/)
-   [Chandler](https://en.wikipedia.org/wiki/Chandler_(software))
-   [iGTD](https://itunes.apple.com/us/app/igtd/id488595283?mt=8)
-   [TiddlyWiki](http://tiddlywiki.com/)

---

## ok, so what is it?<a id="orgheadline11"></a>

`Org-mode` is a major mode for the Emacs text editor.

-   it uses markup to allow for structuring

    * ok, so what is it?                          # heading
    
    =Org-mode= is a major mode for the Emacs text editor.
    - it uses markup to allow for structuring     # unordered list