#+title: R + Org-mode = awesome!
#+date: 2015 November
#+author: John Henderson
#+email: jw.hendy@gmail.com



* setup
  :PROPERTIES:
  :export_file_name: pres_slidify/tcrug_org-mode_slidify.Rmd
  :export_options: toc:nil H:3
  :END:

#+NAME: run-slidify
#+begin_src R :session r :exports none :results silent
slidify("tcrug_org-mode_slidify.Rmd")
#+END_SRC

#+begin_src R :session r :exports none :results silent :eval no

library(slidify)
author("pres_slidify", open_rmd = FALSE, use_git = FALSE)
library(png)
library(grid)

#+end_src

#+BEGIN_MD
---
title       : Org-mode + R = awesome!
subtitle    : 
author      : John Henderson
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---
#+END_MD

** 

#+attr_ravel: echo=F
#+begin_src R :session r :exports results :results output  
img <- readPNG("../img/org-mode.png")
grid.raster(img)
#+end_src

#+RESULTS:

#+md: ---

** the life of a product developer

 Stuff I do in the course of my work (probably not that different from you!):

*** direct
 - write up experimental plans
 - do experiments
 - collect and analyze data
 - writeup reports and presentations
 - collaborate with colleagues

#+md: ---

** the life of a product developer
*** indirect

 - record all sorts info
 - meeting notes
 - todos
 - store contact info/notes
 - what to work on and when


#+md: ---

** but what the hell does emacs have to do with it?

 Believe it or not, I /learned Emacs/ for =org-mode=. To date, it's the /only/ solution I'm
 aware of that allows for all of the following in one place:
 - notes
 - todos/time stamping/deadlines
 - tags
 - embedded code + execution
 - export to multiple formats, with images, links, table of contents, automatically
   generated code blocks and/or results...

 /Pretty cool!/


#+md: ---

** some competition
 I've always been a note taker as I like to refer to the past... you never know what
 might be useful in the future! I tried all sorts of programs:

*** recording work

   - Word/Writer
   - [[http://zim-wiki.org/][zim]] (personal wiki)
   - [[https://evernote.com/][Evernote]]
   - [[http://tiddlywiki.com/][TiddlyWiki]]
   - [[https://www.rstudio.com/][RStudio]]?

#+md: ---

** some competition
*** todos
 - [[http://todotxt.com/][=todo.txt=]]
 - [[https://en.wikipedia.org/wiki/Chandler_(software)][Chandler]]
 - [[https://itunes.apple.com/us/app/igtd/id488595283?mt=8][iGTD]]
 - [[http://tiddlywiki.com/][TiddlyWiki]]

#+md: ---

** ok, so what is it?

 =Org-mode= is a major mode for the Emacs text editor.
 - it uses markup to allow for structuring

#+begin_example
,* ok, so what is it?                          # heading

=Org-mode= is a major mode for the Emacs text editor.
- it uses markup to allow for structuring     # unordered list

#+end_example
